### ISSUE TITLE
Converting a PNG image to JPEG

### ISSUE THREAD

**Issue by alexqzd** [bitbank2/JPEGENC#2]
Is there a way to pipe the output from PNGdec to this library?  
I'm looking for a way to covert a PNG image on an SD card to JPEG and your libraries seem to be the right tools to use.
I'd appreciate it if you could point me to the right direction,
thanks.

**Comment by bitbank2** [comment]
In a word - yes. You'll need both class structures in RAM (64K) and the JPEGDraw function will need to buffer the entire row of MCUs before calling the PNG add row function for the rows. The PNG decoder delivers the native pixel type; for pixel types that are not compatible with the JPEG encoder (e.g. indexed/palette) you'll need to convert them before passing them to the JPEG encoder. What you're asking to do is not complex and will not take that many lines of C code, but if you're not familiar with the pixel types and memory layout it can be confusing.

**Comment by alexqzd** [comment]
Thanks! I checked both libraries examples and now I understand how to make them work together
