### ISSUE TITLE
Issue when trying to decode after encode array from Portenta H7 camera.

### ISSUE THREAD

**Issue by nguterresn** [bitbank2/JPEGENC#3]
Hey! First of all, thanks for the code.

I have been trying to encode and decode JPEG using this library on the Portenta H7:

- GrayScale image from a camera is stored in 76800 bytes (320 * 240 * 1) array.
- Image is compressed...

```c
int compress() {
  rc = jpg.open(ucTemp, sizeof(ucTemp));

  if (rc != JPEG_SUCCESS) {
    return -1;
  }

  rc = jpg.encodeBegin(&jpe, WIDTH, HEIGHT, JPEG_PIXEL_GRAYSCALE, JPEG_SUBSAMPLE_444, JPEG_Q_BEST);
  if (rc != JPEG_SUCCESS) {
    Serial.print("Failed with the code: " );
    Serial.println(rc);
    return -1;
  }
  
  iMCUCount = ((WIDTH + jpe.cx-1)/ jpe.cx) * ((HEIGHT + jpe.cy-1) / jpe.cy);
  for (int i = 0; i < iMCUCount; i++) {
    rc = jpg.addMCU(&jpe, fb_in.getBuffer(), WIDTH);
    if (rc != JPEG_SUCCESS) {
      Serial.print("Failed with the code: " );
      Serial.println(rc);
      return -1;     
    }
  }
  iDataSize = jpg.close();
  return iDataSize;
}
```

Where `fb_in`is the object holding the 76k800 bytes of the camera image.
The WIDTH is set to 320 and the HEIGHT to 240.

The compression returns no error, but then I send the data over the serial port to a python console and when I try to decode the JPEG and show the image, I get this:

https://imgur.com/a/qid6YCi

***

Here is a bit of the pythons code:

```python
from PIL import Image
from io import BytesIO

(... some serial port stuff .. )

sizeOfTheImage = serialPort.readline()
receivedBytes = serialPort.read(int(sizeOfTheImage))

image = Image.open(BytesIO(receivedBytes))
image.show()
```

**Comment by bitbank2** [comment]
The addMCU() method expects to be passed a pointer to the starting pixel of each MCU, not the starting pixel of the whole image. This way you can use a tiny buffer to encode a large image. Your code will need to calculate the correct memory offset for each MCU passed.
