### ISSUE TITLE
question about very low quality endcoding

### ISSUE THREAD

**Issue by krzysztofkuczek** [bitbank2/JPEGENC#4]
Hi,
Very nice project. I wonder if it could support very low quality 4:2:0 jpeg encoding. I'm going to compress 320x200 rgb frame, to size below 3kB. I know that's crazy :)
It's because I'm author of free available system to control unamed RC planes, called Qczek LRS. and i'm going to add experimental support for slow video transmission over a LoRa link. It would be something like 1-2fps 320x200 but it would be cool to make it possible using limited and very small and cheap hardware... Just going to connect SPI capable cammera, encode it's tream and send ...
What do you think?
Kris

You can find out more at the project site https://qczek.beyondrc.com/qczek-lrs-433mhz-1w-lora-rc-link/
Thank you in advance
Kris

**Comment by bitbank2** [comment]
You can modify the code to support an additional step beyond LOW -> "very low". The result of shifting the quantized color values another bit would probably result in the file size you desire. However, the quality would be so low that you would essentially be getting a 1/16th size thumbnail stretched to full size. Each MCU would contain no detail beyond the DC value - a solid color.

**Comment by krzysztofkuczek** [comment]
Thank you.
